version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*/aws-sdk-go"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "boto3"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: weekly
  - package-ecosystem: "docker"
    directory: "/tests/docker"
    schedule:
      interval: weekly
