change:
  - head-branch: ['^change/']

enhancement:
  - head-branch: ['^feature/', '^feat/', '^enhancement/', '^enh/']

bug:
  - head-branch: ['^fix/', '^bug/']

chore:
  - head-branch: ['^chore/']

tests:
  - any:
    - head-branch: ['^tests/', '^test/']
    - changed-files: ['tests/**/*']
  - all:
    - changed-files: ['!tests/requirements.txt']

documentation:
  - head-branch: ['^docs/', '^doc/']
  - changed-files: '**/*.md'

dependencies:
  - head-branch: ['^deps/', '^dep/', '^dependabot/']
  - changed-files: ['go.mod', 'go.sum']
