name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - "feature"
      - "enhancement"
  - title: '💣 Breaking Change'
    labels:
      - "change"
  - title: '🐛 Bug Fixes'
    labels:
      - "bug"
  - title: '📝 Documentation'
    labels:
      - "documentation"
  - title: '🔨 Maintenance'
    labels:
      - "chore"
      - "dependencies"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - 'skip-changelog'
template: |
  ## New in NGINX Plus Integration with Cloud Autoscaling v$RESOLVED_VERSION

  $CHANGES

  ## Resources

  - Documentation -- https://github.com/nginxinc/nginx-asg-sync/blob/v$RESOLVED_VERSION/README.md
