language: go
sudo: required
services:
- docker
go:
- "1.14"
script:
- echo "Nginx ASG sync - commit:${TRAVIS_COMMIT}"
- make BUILD_IN_CONTAINER=0 all
before_install:
- echo "PR Slug:${TRAVIS_PULL_REQUEST_SLUG}"
- if [[ "${TRAVIS_PULL_REQUEST_SLUG}" == "nginxinc/nginx-asg-sync" || "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
  wget https://github.com/fossas/fossa-cli/releases/download/v1.0.30/fossa-cli_1.0.30_linux_amd64.tar.gz && tar xzf fossa-cli_1.0.30_linux_amd64.tar.gz
  && ./fossa init
  && GO111MODULE=on FOSSA_API_KEY=${fossapush} ./fossa analyze -t nginx-asg-sync -b ${TRAVIS_BRANCH} ; fi
