name: "Dependency Review"
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}-deps-review
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-22.04
    permissions:
      contents: read # for actions/checkout
      pull-requests: write # for actions/dependency-review-action to post comments
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: "Dependency Review"
        uses: actions/dependency-review-action@5bbc3ba658137598168acb2ab73b21c432dd411b # v4.2.5
        with:
          config-file: "nginxinc/k8s-common/dependency-review-config.yml@main"
